application: simpleinventory
version: 1
runtime: go
api_version: go1

handlers:



### APP directory for ANGULAR ###

- url: /scripts
  static_dir: app/scripts

- url: /styles
  static_dir: app/styles

- url: /bower_components
  static_dir: app/bower_components

- url: /views
  static_dir: app/views


- url: /.*
  script: _go_app